### ISSUE TITLE
Problem with armbian an docker

### ISSUE THREAD

**Issue by maxlinux2000** [MajorcaDevs/docker-icecast#1]
Hello
I write to you in English although Spanish is better for me.

I have a problem with your icecast image ... I can't get Enviroment variables to be used to create an icecast.xml with my data.

I am using:
docker-compose version 1.21.0
and I can't put a higher version because it doesn't work for me in armbian, so I'm using the one that comes by default, and therefore won't let me use docker-compose.yml version 3.7
(my board is a 2GB orangePI3)

So I'm trying to create a '2' version

My system has Portainer installed and Traefik1.7 to manage the various container ... icecast works and is visible to the outside (with ssl from letsencrypt, also)
But it does not take the variables, although Portainer tells me that he is using it.
I assume icecast.xml is created before the variables are loaded.
I put my docker-compose.yml here

```
version: '2'
services:
  icecast:
    image: majorcadevs/icecast
    ports:
      - "8000:8000"
    restart: always
    networks:
      - web
    environment: 
     - GENERATE_TEMPLATE=True
     - IC_RELAY_MASTER_SERVER=master
     - IC_RELAY_MASTER_UPDATE_INTERVAL=30
     - IC_ADMIN=max@gmail.com
     - IC_ADMIN_PASSWORD=MyPass
     - IC_ADMIN_USER=admin
     - IC_CLIENT_TIMEOUT=30
     - IC_HEADER_TIMEOUT=15
     - IC_HOSTNAME=mydomain.org
     - IC_LISTEN_BIND_ADDRESS=0.0.0.0
     - IC_LISTEN_MOUNT=stream
     - IC_LISTEN_PORT=8000
     - IC_LOCATION=España
     - IC_MAX_CLIENTS=100
     - IC_MAX_SOURCES=4
     - IC_SOURCE_PASSWORD=MyPass
     - IC_SOURCE_TIMEOUT=10
     - RADIO_MOUNT_NAME=stream
     - RADIO_NAME=icecast.radio
     - RADIO_WEBSITE=https://mydomain.org
     - GENRE=catholic
     - GENERATE_TEMPLATE=False
     - IC_QUEUE_SIZE=524288
     - IC_BURST_SIZE=65535
     - IC_MASTER_RELAY_PASSWORD=MyPass
     - ENABLE_RELAY=False
     - IC_RELAY_MASTER_SERVER=changeme
     - IC_RELAY_MASTER_PORT=8000
     - IC_RELAY_MASTER_UPDATE_INTERVAL=120
     - IC_RELAY_MASTER_PASSWORD=MyPass
     - IC_DEBUG_LOGLEVEL=3
     - IC_LOGSIZE=10000
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:mydomain.org"
      - "traefik.docker.network=web"
networks:
  web:
    external: true

```
